### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by lkarvec**
### Premise
White is blinding.  We were wrong when we said "let there be light".  This PR assists turning the dimmers on.
I also have some prep for other UI refactors later on.  Mainly fixing Group and Text.

### Before Screenshot
image
image
image

### After Screenshot
image
image
image
image

### Change Log
- Changed Group to allow for more flexibility in spacing between groups with the new prop `skipSpace`
- added styling for react-selects with a different prefix, so that we can more easily apply styles with CSS
- Prettiered (autoformatting to ease up linting errors/style errors) some files while I was going through things, so if theres things you want unprettiered, let me know and I'll fix.  I already see some dumb auto-formatting in expr.ts and tricks.ts tbh which it did for readability.
- added the darkmode toggle on the bottom of the sidebar
- Added a label check on dropdowns so they aren't perma rendered and causing style issues.
- added some manual styles to certain selects, like Hints selects to increase padding for mobile responsiveness.
- added a way to set darkmode context with localstorage (unsure if this works).  There is also a way for Dark mode to be read in automatically if the localstorage data doesn't exist, based on system preference.
- adjusted general colors on the site, including the bootstrap styles, body,  select, textarea, and a bunch of other things around.  We use those very cool variables in the css sheets for this now like `--background` and `--color`

### Things that should be done next

- Bigger UI overhaul to bring in more responsiveness and swap the site's other node elements to bootstrap, that way we have better control over styles if we want to overhaul more UI in the future (I do).
- Move Glitches UI to use the Selector Card.
- Expand the documentation for Tricks as we go.
- Fix really ugly checkbox resizing issue that is really apparent here

### CODE REVIEW

**Comment by CelestialKitsune** [comment]
Apologies for taking this long to even notice this was here. Could you rebase and fix the conflicts please? I'll take a look afterwards! Don't hesitate to ping me on Discord once there is not more conflict!

**Comment by CelestialKitsune** [comment]
> Apologies for taking this long to even notice this was here. Could you rebase and fix the conflicts please? I'll take a look afterwards! Don't hesitate to ping me on Discord once there is not more conflict!

@lkarvec any ETA on this?

**Comment by Nax** [comment]
Closing for inactivity (sorry for taking a bit long to handle the PR, plus I think you made it when we were doing quite the changes to the UI). Can always reopen later.

**Comment by lkarvec** [comment]
Yeah sorry, I'm really busy with work at the moment so I don't really have all too much time to fix this right now.  If we're not using the Bootstrap components, then I have to redo quite a lot with the branch.

**Pull request closed without merging**
